-- Create comprehensive content for A2 level courses

-- A2 Past Experiences
UPDATE lessons SET content = CASE 
  WHEN title LIKE '%Introduction%' AND EXISTS (SELECT 1 FROM courses WHERE courses.id = lessons.course_id AND courses.level = 'A2' AND courses.title = 'Past Experiences') THEN
    E'# Introduction to Past Experiences\n\n## Learning Objectives\nBy the end of this lesson, you will be able to:\n- Talk about past events and experiences using past tense\n- Use time expressions for past events\n- Ask and answer questions about past experiences\n- Tell simple stories about your life\n\n## Key Vocabulary\n**Time Expressions:**\n- Yesterday, last week, last month, last year\n- Ago (two days ago, a week ago)\n- When I was young, in the past\n- Already, yet, just, never, ever\n\n**Experience Verbs:**\n- Traveled, visited, lived, worked, studied\n- Met, saw, heard, felt, thought\n- Started, finished, completed, achieved\n\n## Grammar Focus\n- Simple Past Tense (regular and irregular verbs)\n- Past Continuous Tense (was/were + -ing)\n- Present Perfect for experiences (have/has + past participle)\n- Time expressions with past tenses\n\n## Common Question Patterns\n- When did you...?\n- Have you ever...?\n- What did you do...?\n- Where were you...?\n- How long ago did you...?'
  
  WHEN title LIKE '%Core Concepts%' AND EXISTS (SELECT 1 FROM courses WHERE courses.id = lessons.course_id AND courses.level = 'A2' AND courses.title = 'Past Experiences') THEN
    E'# Core Concepts: Past Experiences\n\n## Simple Past Tense\n\n### Regular Verbs\n- Walk → walked\n- Visit → visited\n- Study → studied\n- Live → lived\n- Work → worked\n\n### Irregular Verbs\n- Go → went\n- See → saw\n- Have → had\n- Come → came\n- Take → took\n- Make → made\n- Get → got\n\n### Past Tense Questions\n- Did you go to the party?\n- Where did you travel last summer?\n- What time did you wake up?\n\n## Present Perfect for Experiences\n\n### Structure: have/has + past participle\n- I have traveled to Japan\n- She has lived in three countries\n- We have never seen that movie\n\n### Experience Questions\n- Have you ever been to Paris?\n- Has she finished her homework?\n- Have they visited the museum?\n\n## Time Expressions\n\n### With Simple Past\n- Yesterday I went shopping\n- Last week we had a party\n- Two years ago I started university\n\n### With Present Perfect\n- I have already eaten lunch\n- She has not finished yet\n- Have you ever been abroad?\n\n## Storytelling Phrases\n- First, then, after that, finally\n- Suddenly, meanwhile, at the same time\n- It was amazing/terrible/interesting\n- I will never forget when...'
  
  WHEN title LIKE '%Practice%' AND EXISTS (SELECT 1 FROM courses WHERE courses.id = lessons.course_id AND courses.level = 'A2' AND courses.title = 'Past Experiences') THEN
    E'# Practice & Application: Past Experiences\n\n## Story Practice\n\n### My Last Vacation\n**Tell your story using these prompts:**\n- Where did you go?\n- How long did you stay?\n- Who did you travel with?\n- What did you do there?\n- What was the best part?\n- Would you go back?\n\n### Sample Story:\n"Last summer, I went to Italy with my family. We stayed for two weeks and visited Rome, Florence, and Venice. I had never been to Europe before, so everything was new and exciting. We saw amazing art, ate delicious food, and met friendly people. The best part was seeing the Colosseum - it was incredible! I have already started planning my next trip back."\n\n## Dialogue Practice\n\n### Job Interview - Past Experience\n**Interviewer:** Tell me about your previous work experience.\n**Candidate:** I worked at ABC Company for three years. I started as a junior assistant and was promoted to team leader. I managed five people and completed several important projects.\n**Interviewer:** What was your biggest achievement there?\n**Candidate:** I successfully organized a conference for 200 people. It was challenging, but we received excellent feedback.\n\n## Common Mistakes\n\n1. **Mixing tenses incorrectly**\n   - Wrong: "Yesterday I have gone to the store"\n   - Correct: "Yesterday I went to the store"\n\n2. **Forgetting irregular verb forms**\n   - Wrong: "I goed to school"\n   - Correct: "I went to school"\n\n3. **Using present perfect with specific time**\n   - Wrong: "I have visited Paris last year"\n   - Correct: "I visited Paris last year"'
  
  WHEN title LIKE '%Review%' AND EXISTS (SELECT 1 FROM courses WHERE courses.id = lessons.course_id AND courses.level = 'A2' AND courses.title = 'Past Experiences') THEN
    E'# Review & Assessment: Past Experiences\n\n## Grammar Summary\n\n### Simple Past Usage\n- Completed actions in the past with specific time\n- "I graduated in 2020"\n- "She lived in Tokyo from 2015 to 2018"\n\n### Present Perfect Usage\n- Experiences without specific time\n- "I have been to Japan" (sometime in my life)\n- Actions that started in the past and continue now\n- "I have lived here for five years" (still living here)\n\n### Past Continuous Usage\n- Actions in progress at a specific past time\n- "I was studying when you called"\n- Setting the scene in stories\n- "It was raining, and people were hurrying home"\n\n## Self-Assessment Questions\n\n☐ Can I tell a simple story about my past?\n☐ Do I know the difference between simple past and present perfect?\n☐ Can I use time expressions correctly?\n☐ Do I know common irregular past tenses?\n☐ Can I ask questions about past experiences?\n\n## Useful Expressions for Experiences\n\n**Positive Experiences:**\n- It was amazing/wonderful/fantastic\n- I really enjoyed it\n- It was the best experience of my life\n- I learned so much\n\n**Negative Experiences:**\n- It was terrible/awful/disappointing\n- I did not enjoy it at all\n- It was a waste of time\n- I regret doing it\n\n**Neutral/Mixed Experiences:**\n- It was OK/alright\n- It was interesting but challenging\n- I am glad I tried it\n- It was a learning experience\n\n## Practice Exercises\n1. Write about your best childhood memory\n2. Describe your first day at work/school\n3. Tell about a time you helped someone\n4. Share an experience that changed your mind about something'

  ELSE content
END
WHERE EXISTS (SELECT 1 FROM courses WHERE courses.id = lessons.course_id AND courses.level = 'A2' AND courses.title = 'Past Experiences');

-- A2 Travel & Directions  
UPDATE lessons SET content = CASE 
  WHEN title LIKE '%Introduction%' AND EXISTS (SELECT 1 FROM courses WHERE courses.id = lessons.course_id AND courses.level = 'A2' AND courses.title = 'Travel & Directions') THEN
    E'# Introduction to Travel & Directions\n\n## Learning Objectives\nBy the end of this lesson, you will be able to:\n- Ask for and give directions clearly\n- Use transportation vocabulary\n- Make travel arrangements and bookings\n- Describe locations and landmarks\n- Handle common travel situations\n\n## Key Vocabulary\n\n**Transportation:**\n- Bus, train, plane, taxi, subway, ferry\n- Bicycle, motorcycle, car, walking\n- Ticket, boarding pass, platform, terminal\n- Station, airport, bus stop, taxi rank\n\n**Directions:**\n- Turn left/right, go straight, go back\n- North, south, east, west\n- Next to, opposite, between, behind, in front of\n- At the corner, at the traffic lights, at the roundabout\n\n**Travel Essentials:**\n- Passport, visa, luggage, backpack\n- Hotel, hostel, bed and breakfast\n- Check-in, check-out, reservation, booking\n- Map, GPS, guidebook, tourist information\n\n## Grammar Focus\n- Prepositions of place and direction\n- Imperative form for giving directions\n- Future forms for travel plans (going to, will)\n- Questions with "How do I get to...?" and "Where is...?"'
  
  WHEN title LIKE '%Core Concepts%' AND EXISTS (SELECT 1 FROM courses WHERE courses.id = lessons.course_id AND courses.level = 'A2' AND courses.title = 'Travel & Directions') THEN
    E'# Core Concepts: Travel & Directions\n\n## Giving Directions\n\n### Basic Direction Phrases\n- Go straight ahead\n- Turn left at the next corner\n- Turn right at the traffic lights\n- Take the first/second/third street on the left\n- Cross the street/bridge\n- Walk past the bank\n- It is on your left/right\n\n### Distance and Time\n- It is about 5 minutes on foot\n- It is 200 meters from here\n- It is quite far/close/nearby\n- You cannot miss it\n- It is just around the corner\n\n## Asking for Directions\n\n### Polite Questions\n- Excuse me, how do I get to the train station?\n- Could you tell me the way to the museum?\n- Is this the right way to the airport?\n- How far is it to the city center?\n- Am I going in the right direction?\n\n### Understanding Responses\n- I am sorry, I do not know\n- I am not from around here\n- You are going the wrong way\n- It is better to take a taxi\n- Let me show you on the map\n\n## Transportation\n\n### Public Transport\n- Which bus goes to the airport?\n- What time does the next train leave?\n- How much is a ticket to downtown?\n- Do I need to change trains?\n- Which platform for the London train?\n\n### Booking and Reservations\n- I would like to book a room\n- Do you have any availability?\n- I have a reservation under the name Smith\n- Can I change my booking?\n- What time is check-in?\n\n## Travel Problems\n\n### Common Issues\n- I am lost\n- I missed my flight/train\n- My luggage is missing\n- The hotel cancelled my reservation\n- I do not have enough money\n\n### Getting Help\n- Can you help me, please?\n- Is there a tourist information center?\n- Where is the nearest police station?\n- I need to call my embassy\n- Do you speak English?'
  
  ELSE content
END
WHERE EXISTS (SELECT 1 FROM courses WHERE courses.id = lessons.course_id AND courses.level = 'A2' AND courses.title = 'Travel & Directions');