-- Create lessons for A1 course (using the ID from previous result)
INSERT INTO lessons (course_id, title, content, order_index) 
SELECT 'f3e17a99-681c-4258-8c3c-b083d5efb0c5' as course_id, title, content, order_index FROM (VALUES
  ('Meet and Greet + Verb To Be', '<h2>Learning Objectives</h2><p>Learn basic greetings and master the verb "to be"</p><h3>Grammar Focus: Verb To Be</h3><p><strong>Positive:</strong> I am, you are, he/she/it is, we are, they are</p><p><strong>Negative:</strong> I am not, you are not, he is not, etc.</p><p><strong>Questions:</strong> Are you...? Is he...? Are they...?</p><h3>Vocabulary: Greetings</h3><ul><li>Hello / Hi</li><li>Good morning / afternoon / evening</li><li>How are you?</li><li>Nice to meet you</li><li>Goodbye / Bye</li></ul>', 1),
  ('Countries and Nationalities + Verb To Be Drills', '<h2>Countries and Nationalities</h2><p>Learn to talk about where you are from</p><h3>Key Vocabulary</h3><ul><li>Brazil - Brazilian</li><li>United States - American</li><li>United Kingdom - British</li><li>France - French</li><li>Germany - German</li><li>Spain - Spanish</li><li>Italy - Italian</li><li>Japan - Japanese</li></ul><h3>Grammar Pattern</h3><p>I am from Brazil. I am Brazilian.</p><p>She is from France. She is French.</p>', 2),
  ('Simple Present (I/you/we/they)', '<h2>Simple Present Tense</h2><p>Learn to express habits, facts, and general truths</p><h3>Formation</h3><p><strong>Positive:</strong> I/You/We/They + verb</p><p><strong>Negative:</strong> I/You/We/They + do not (don''t) + verb</p><p><strong>Questions:</strong> Do + I/you/we/they + verb?</p><h3>Examples</h3><ul><li>I work in an office.</li><li>You speak English well.</li><li>We live in São Paulo.</li><li>They don''t like coffee.</li></ul>', 3),
  ('Simple Present (he/she/it)', '<h2>Simple Present: Third Person Singular</h2><p>Learn the special rules for he/she/it</p><h3>Formation</h3><p><strong>Positive:</strong> He/She/It + verb + s/es</p><p><strong>Negative:</strong> He/She/It + does not (doesn''t) + verb</p><p><strong>Questions:</strong> Does + he/she/it + verb?</p><h3>Examples</h3><ul><li>He works at a bank.</li><li>She studies English every day.</li><li>It doesn''t rain much here.</li><li>Does he like pizza?</li></ul>', 4),
  ('Wh Questions + Days of the Week', '<h2>Question Words (Wh- Questions)</h2><p>Learn to ask for specific information</p><h3>Question Words</h3><ul><li>What - for things</li><li>Where - for places</li><li>When - for time</li><li>Who - for people</li><li>Why - for reasons</li><li>How - for manner</li></ul><h3>Days of the Week</h3><ul><li>Monday</li><li>Tuesday</li><li>Wednesday</li><li>Thursday</li><li>Friday</li><li>Saturday</li><li>Sunday</li></ul>', 5),
  ('Numbers 1-100 + How Old...?', '<h2>Numbers and Age</h2><p>Learn numbers from 1 to 100 and how to ask about age</p><h3>Numbers 1-20</h3><p>1-one, 2-two, 3-three, 4-four, 5-five, 6-six, 7-seven, 8-eight, 9-nine, 10-ten, 11-eleven, 12-twelve, 13-thirteen, 14-fourteen, 15-fifteen, 16-sixteen, 17-seventeen, 18-eighteen, 19-nineteen, 20-twenty</p><h3>Asking About Age</h3><p>How old are you? I am 25 years old.</p><p>How old is she? She is 30.</p>', 6),
  ('Adverbs of Frequency + Months', '<h2>How Often?</h2><p>Express how frequently you do things</p><h3>Adverbs of Frequency</h3><ul><li>Always (100%)</li><li>Usually (90%)</li><li>Often (70%)</li><li>Sometimes (50%)</li><li>Rarely (10%)</li><li>Never (0%)</li></ul><h3>Months of the Year</h3><p>January, February, March, April, May, June, July, August, September, October, November, December</p>', 7),
  ('Family Members + Possessive Adjectives', '<h2>Family Vocabulary</h2><p>Talk about your family members</p><h3>Family Members</h3><ul><li>Mother/Mom, Father/Dad</li><li>Sister, Brother</li><li>Grandmother, Grandfather</li><li>Aunt, Uncle</li><li>Cousin</li></ul><h3>Possessive Adjectives</h3><p>My, Your, His, Her, Its, Our, Their</p><p>Example: This is my mother. Her name is Maria.</p>', 8),
  ('There To Be in the Present', '<h2>There Is / There Are</h2><p>Describe what exists in a place</p><h3>Usage</h3><p><strong>There is</strong> + singular noun</p><p><strong>There are</strong> + plural noun</p><h3>Examples</h3><ul><li>There is a book on the table.</li><li>There are three cats in the garden.</li><li>Is there a bank near here?</li><li>Are there any restaurants?</li></ul>', 9),
  ('This/That/These/Those + Saying the Price', '<h2>Demonstratives and Prices</h2><p>Point to things and talk about prices</p><h3>Demonstratives</h3><ul><li>This (near/singular)</li><li>That (far/singular)</li><li>These (near/plural)</li><li>Those (far/plural)</li></ul><h3>Talking About Prices</h3><p>How much is this? It''s $10.</p><p>How much are these? They''re $25.</p>', 10),
  ('Possessive ''s + Adjectives and Colors', '<h2>Showing Ownership and Describing Things</h2><h3>Possessive ''s</h3><p>John''s car, Maria''s house, the children''s toys</p><h3>Colors</h3><p>Red, blue, green, yellow, black, white, brown, pink, purple, orange, gray</p><h3>Basic Adjectives</h3><p>Big/small, old/new, hot/cold, good/bad, expensive/cheap</p>', 11),
  ('Verb To Be in the Past + Drills', '<h2>Past Tense of "Be"</h2><p>Talk about past situations and states</p><h3>Past Forms</h3><p>I was, You were, He/She/It was, We were, They were</p><h3>Negative</h3><p>I wasn''t, You weren''t, He wasn''t, We weren''t, They weren''t</p><h3>Questions</h3><p>Was I...? Were you...? Was he...?</p>', 12),
  ('Verb To Be Past + Time Expressions', '<h2>Past Time Expressions</h2><p>Specify when something happened in the past</p><h3>Time Expressions</h3><ul><li>Yesterday</li><li>Last night/week/month/year</li><li>This morning (if it''s afternoon/evening)</li><li>Two days/weeks/months ago</li><li>In 2020, In January</li></ul>', 13),
  ('Simple Past - Affirmative Sentences', '<h2>Past Actions and Events</h2><p>Talk about completed actions in the past</p><h3>Regular Verbs</h3><p>Add -ed: worked, played, studied, watched</p><h3>Irregular Verbs</h3><ul><li>go → went</li><li>see → saw</li><li>eat → ate</li><li>drink → drank</li><li>come → came</li></ul>', 14),
  ('Simple Past Negative + Transportation', '<h2>What Didn''t Happen</h2><p>Express negative past actions</p><h3>Formation</h3><p>Subject + didn''t + base verb</p><p>I didn''t go to work yesterday.</p><h3>Transportation Vocabulary</h3><ul><li>Car, bus, train, plane, bike</li><li>Walk, drive, fly, take the bus</li><li>Airport, station, traffic</li></ul>', 15),
  ('Simple Past Questions + Seasons and Weather', '<h2>Asking About the Past</h2><p>Form questions about past events</p><h3>Yes/No Questions</h3><p>Did you go to the party? Yes, I did. / No, I didn''t.</p><h3>Wh- Questions</h3><p>Where did you go? What did you eat?</p><h3>Weather and Seasons</h3><ul><li>Spring, Summer, Fall/Autumn, Winter</li><li>Sunny, rainy, cloudy, windy, hot, cold</li></ul>', 16),
  ('Numbers 101-1000 + Years', '<h2>Large Numbers and Years</h2><p>Count higher and talk about years</p><h3>Numbers 101-1000</h3><p>101-one hundred and one, 150-one hundred and fifty, 200-two hundred, 1000-one thousand</p><h3>Years</h3><p>1990 = nineteen ninety</p><p>2000 = two thousand</p><p>2021 = twenty twenty-one</p>', 17),
  ('Object Pronouns', '<h2>Replace Nouns with Pronouns</h2><p>Use pronouns to avoid repetition</p><h3>Object Pronouns</h3><p>Me, You, Him, Her, It, Us, Them</p><h3>Examples</h3><ul><li>I like John. → I like him.</li><li>Call Maria. → Call her.</li><li>Give the books to the students. → Give them to them.</li></ul>', 18),
  ('Can for Ability + Past Time Activities', '<h2>Expressing Ability</h2><p>Talk about what you can and can''t do</p><h3>Modal Verb: Can</h3><p><strong>Positive:</strong> I can swim.</p><p><strong>Negative:</strong> I can''t drive.</p><p><strong>Question:</strong> Can you speak Spanish?</p><h3>Past Time Activities</h3><p>Yesterday I played soccer, watched TV, cooked dinner, read a book</p>', 19),
  ('Going To + Future Time Expressions', '<h2>Future Plans and Intentions</h2><p>Talk about your future plans</p><h3>Be Going To</h3><p>I am going to travel next month.</p><p>She is going to study tonight.</p><p>Are you going to come to the party?</p><h3>Future Time Expressions</h3><ul><li>Tomorrow, Next week/month/year</li><li>This evening/weekend</li><li>In two hours/days</li></ul>', 20)
) AS lesson_data(title, content, order_index);