-- Clear existing courses and related data
DELETE FROM user_lesson_progress;
DELETE FROM user_exercise_attempts;
DELETE FROM lesson_content;
DELETE FROM exercises;
DELETE FROM lessons;
DELETE FROM courses;

-- Create new level-based courses
INSERT INTO courses (id, title, description, level, order_index) VALUES
  ('a1-course-id', 'English Foundations - A1', 'Master the basics: greetings, present tense, numbers, family, and everyday situations. Based on Cambridge Empower A1.', 'A1', 1),
  ('a2-course-id', 'Elementary English - A2', 'Build on fundamentals with countable/uncountable nouns, preferences, continuous tenses, and basic conditionals.', 'A2', 2),
  ('b1-course-id', 'Pre-Intermediate English - B1', 'Develop intermediate skills with perfect tenses, modal verbs, and complex sentence structures.', 'B1', 3),
  ('b2-course-id', 'Upper-Intermediate English - B2', 'Advanced grammar including future perfect, passive voice, and relative clauses. Prepare for professional communication.', 'B2', 4),
  ('c1-course-id', 'Advanced English - C1', 'Master complex grammar, reported speech, idioms, and sophisticated writing techniques.', 'C1', 5),
  ('c2-course-id', 'Proficiency English - C2', 'Achieve near-native fluency with nuanced language use, advanced discourse markers, and literary analysis.', 'C2', 6);

-- A1 Course Lessons (Basic Level - 20 lessons)
INSERT INTO lessons (id, course_id, title, content, order_index) VALUES
  ('a1-l1', 'a1-course-id', 'Meet and Greet + Verb To Be', '<h2>Learning Objectives</h2><p>Learn basic greetings and master the verb "to be"</p><h3>Grammar Focus: Verb To Be</h3><p><strong>Positive:</strong> I am, you are, he/she/it is, we are, they are</p><p><strong>Negative:</strong> I am not, you are not, he is not, etc.</p><p><strong>Questions:</strong> Are you...? Is he...? Are they...?</p><h3>Vocabulary: Greetings</h3><ul><li>Hello / Hi</li><li>Good morning / afternoon / evening</li><li>How are you?</li><li>Nice to meet you</li><li>Goodbye / Bye</li></ul>', 1),
  ('a1-l2', 'a1-course-id', 'Countries and Nationalities + Verb To Be Drills', '<h2>Countries and Nationalities</h2><p>Learn to talk about where you are from</p><h3>Key Vocabulary</h3><ul><li>Brazil - Brazilian</li><li>United States - American</li><li>United Kingdom - British</li><li>France - French</li><li>Germany - German</li><li>Spain - Spanish</li><li>Italy - Italian</li><li>Japan - Japanese</li></ul><h3>Grammar Pattern</h3><p>I am from Brazil. I am Brazilian.</p><p>She is from France. She is French.</p>', 2),
  ('a1-l3', 'a1-course-id', 'Simple Present (I/you/we/they)', '<h2>Simple Present Tense</h2><p>Learn to express habits, facts, and general truths</p><h3>Formation</h3><p><strong>Positive:</strong> I/You/We/They + verb</p><p><strong>Negative:</strong> I/You/We/They + do not (don''t) + verb</p><p><strong>Questions:</strong> Do + I/you/we/they + verb?</p><h3>Examples</h3><ul><li>I work in an office.</li><li>You speak English well.</li><li>We live in São Paulo.</li><li>They don''t like coffee.</li></ul>', 3),
  ('a1-l4', 'a1-course-id', 'Simple Present (he/she/it)', '<h2>Simple Present: Third Person Singular</h2><p>Learn the special rules for he/she/it</p><h3>Formation</h3><p><strong>Positive:</strong> He/She/It + verb + s/es</p><p><strong>Negative:</strong> He/She/It + does not (doesn''t) + verb</p><p><strong>Questions:</strong> Does + he/she/it + verb?</p><h3>Examples</h3><ul><li>He works at a bank.</li><li>She studies English every day.</li><li>It doesn''t rain much here.</li><li>Does he like pizza?</li></ul>', 4),
  ('a1-l5', 'a1-course-id', 'Wh Questions + Days of the Week', '<h2>Question Words (Wh- Questions)</h2><p>Learn to ask for specific information</p><h3>Question Words</h3><ul><li>What - for things</li><li>Where - for places</li><li>When - for time</li><li>Who - for people</li><li>Why - for reasons</li><li>How - for manner</li></ul><h3>Days of the Week</h3><ul><li>Monday</li><li>Tuesday</li><li>Wednesday</li><li>Thursday</li><li>Friday</li><li>Saturday</li><li>Sunday</li></ul>', 5),
  ('a1-l6', 'a1-course-id', 'Numbers 1-100 + How Old...?', '<h2>Numbers and Age</h2><p>Learn numbers from 1 to 100 and how to ask about age</p><h3>Numbers 1-20</h3><p>1-one, 2-two, 3-three, 4-four, 5-five, 6-six, 7-seven, 8-eight, 9-nine, 10-ten, 11-eleven, 12-twelve, 13-thirteen, 14-fourteen, 15-fifteen, 16-sixteen, 17-seventeen, 18-eighteen, 19-nineteen, 20-twenty</p><h3>Asking About Age</h3><p>How old are you? I am 25 years old.</p><p>How old is she? She is 30.</p>', 6),
  ('a1-l7', 'a1-course-id', 'Adverbs of Frequency + Months', '<h2>How Often?</h2><p>Express how frequently you do things</p><h3>Adverbs of Frequency</h3><ul><li>Always (100%)</li><li>Usually (90%)</li><li>Often (70%)</li><li>Sometimes (50%)</li><li>Rarely (10%)</li><li>Never (0%)</li></ul><h3>Months of the Year</h3><p>January, February, March, April, May, June, July, August, September, October, November, December</p>', 7),
  ('a1-l8', 'a1-course-id', 'Family Members + Possessive Adjectives', '<h2>Family Vocabulary</h2><p>Talk about your family members</p><h3>Family Members</h3><ul><li>Mother/Mom, Father/Dad</li><li>Sister, Brother</li><li>Grandmother, Grandfather</li><li>Aunt, Uncle</li><li>Cousin</li></ul><h3>Possessive Adjectives</h3><p>My, Your, His, Her, Its, Our, Their</p><p>Example: This is my mother. Her name is Maria.</p>', 8),
  ('a1-l9', 'a1-course-id', 'There To Be in the Present', '<h2>There Is / There Are</h2><p>Describe what exists in a place</p><h3>Usage</h3><p><strong>There is</strong> + singular noun</p><p><strong>There are</strong> + plural noun</p><h3>Examples</h3><ul><li>There is a book on the table.</li><li>There are three cats in the garden.</li><li>Is there a bank near here?</li><li>Are there any restaurants?</li></ul>', 9),
  ('a1-l10', 'a1-course-id', 'This/That/These/Those + Saying the Price', '<h2>Demonstratives and Prices</h2><p>Point to things and talk about prices</p><h3>Demonstratives</h3><ul><li>This (near/singular)</li><li>That (far/singular)</li><li>These (near/plural)</li><li>Those (far/plural)</li></ul><h3>Talking About Prices</h3><p>How much is this? It''s $10.</p><p>How much are these? They''re $25.</p>', 10),
  ('a1-l11', 'a1-course-id', 'Possessive ''s + Adjectives and Colors', '<h2>Showing Ownership and Describing Things</h2><h3>Possessive ''s</h3><p>John''s car, Maria''s house, the children''s toys</p><h3>Colors</h3><p>Red, blue, green, yellow, black, white, brown, pink, purple, orange, gray</p><h3>Basic Adjectives</h3><p>Big/small, old/new, hot/cold, good/bad, expensive/cheap</p>', 11),
  ('a1-l12', 'a1-course-id', 'Verb To Be in the Past + Drills', '<h2>Past Tense of "Be"</h2><p>Talk about past situations and states</p><h3>Past Forms</h3><p>I was, You were, He/She/It was, We were, They were</p><h3>Negative</h3><p>I wasn''t, You weren''t, He wasn''t, We weren''t, They weren''t</p><h3>Questions</h3><p>Was I...? Were you...? Was he...?</p>', 12),
  ('a1-l13', 'a1-course-id', 'Verb To Be Past + Time Expressions', '<h2>Past Time Expressions</h2><p>Specify when something happened in the past</p><h3>Time Expressions</h3><ul><li>Yesterday</li><li>Last night/week/month/year</li><li>This morning (if it''s afternoon/evening)</li><li>Two days/weeks/months ago</li><li>In 2020, In January</li></ul>', 13),
  ('a1-l14', 'a1-course-id', 'Simple Past - Affirmative Sentences', '<h2>Past Actions and Events</h2><p>Talk about completed actions in the past</p><h3>Regular Verbs</h3><p>Add -ed: worked, played, studied, watched</p><h3>Irregular Verbs</h3><ul><li>go → went</li><li>see → saw</li><li>eat → ate</li><li>drink → drank</li><li>come → came</li></ul>', 14),
  ('a1-l15', 'a1-course-id', 'Simple Past Negative + Transportation', '<h2>What Didn''t Happen</h2><p>Express negative past actions</p><h3>Formation</h3><p>Subject + didn''t + base verb</p><p>I didn''t go to work yesterday.</p><h3>Transportation Vocabulary</h3><ul><li>Car, bus, train, plane, bike</li><li>Walk, drive, fly, take the bus</li><li>Airport, station, traffic</li></ul>', 15),
  ('a1-l16', 'a1-course-id', 'Simple Past Questions + Seasons and Weather', '<h2>Asking About the Past</h2><p>Form questions about past events</p><h3>Yes/No Questions</h3><p>Did you go to the party? Yes, I did. / No, I didn''t.</p><h3>Wh- Questions</h3><p>Where did you go? What did you eat?</p><h3>Weather and Seasons</h3><ul><li>Spring, Summer, Fall/Autumn, Winter</li><li>Sunny, rainy, cloudy, windy, hot, cold</li></ul>', 16),
  ('a1-l17', 'a1-course-id', 'Numbers 101-1000 + Years', '<h2>Large Numbers and Years</h2><p>Count higher and talk about years</p><h3>Numbers 101-1000</h3><p>101-one hundred and one, 150-one hundred and fifty, 200-two hundred, 1000-one thousand</p><h3>Years</h3><p>1990 = nineteen ninety</p><p>2000 = two thousand</p><p>2021 = twenty twenty-one</p>', 17),
  ('a1-l18', 'a1-course-id', 'Object Pronouns', '<h2>Replace Nouns with Pronouns</h2><p>Use pronouns to avoid repetition</p><h3>Object Pronouns</h3><p>Me, You, Him, Her, It, Us, Them</p><h3>Examples</h3><ul><li>I like John. → I like him.</li><li>Call Maria. → Call her.</li><li>Give the books to the students. → Give them to them.</li></ul>', 18),
  ('a1-l19', 'a1-course-id', 'Can for Ability + Past Time Activities', '<h2>Expressing Ability</h2><p>Talk about what you can and can''t do</p><h3>Modal Verb: Can</h3><p><strong>Positive:</strong> I can swim.</p><p><strong>Negative:</strong> I can''t drive.</p><p><strong>Question:</strong> Can you speak Spanish?</p><h3>Past Time Activities</h3><p>Yesterday I played soccer, watched TV, cooked dinner, read a book</p>', 19),
  ('a1-l20', 'a1-course-id', 'Going To + Future Time Expressions', '<h2>Future Plans and Intentions</h2><p>Talk about your future plans</p><h3>Be Going To</h3><p>I am going to travel next month.</p><p>She is going to study tonight.</p><p>Are you going to come to the party?</p><h3>Future Time Expressions</h3><ul><li>Tomorrow, Next week/month/year</li><li>This evening/weekend</li><li>In two hours/days</li></ul>', 20);

-- A2 Course Lessons (Elementary Level - 20 lessons)
INSERT INTO lessons (id, course_id, title, content, order_index) VALUES
  ('a2-l1', 'a2-course-id', 'Review: Verb Tenses and Pronouns', '<h2>Previously on Basic Level...</h2><p>Comprehensive review of A1 grammar</p><h3>Review Topics</h3><ul><li>Present Simple vs Present Continuous</li><li>Past Simple vs Past Continuous</li><li>Subject and Object Pronouns</li><li>Possessive Adjectives vs Possessive Pronouns</li></ul><p><strong>Practice:</strong> Complete mixed tense exercises to solidify your foundation.</p>', 1),
  ('a2-l2', 'a2-course-id', 'Countable/Uncountable + Quantifiers', '<h2>Counting and Measuring</h2><p>Learn the difference between countable and uncountable nouns</p><h3>Countable Nouns</h3><p>apple/apples, book/books, person/people</p><h3>Uncountable Nouns</h3><p>water, money, advice, information</p><h3>Quantifiers</h3><ul><li>Some, any, much, many</li><li>A lot of, lots of, a few, a little</li></ul><h3>Food Vocabulary</h3><p>bread, cheese, meat, vegetables, fruit, rice, pasta</p>', 2),
  ('a2-l3', 'a2-course-id', 'Preference Verbs', '<h2>Expressing Likes and Dislikes</h2><p>Talk about your preferences</p><h3>Preference Verbs</h3><ul><li>Like/dislike + noun/gerund</li><li>Love/hate + noun/gerund</li><li>Prefer + noun/gerund</li><li>Would rather + base verb</li></ul><h3>Vocabulary</h3><p>Food: pizza, sushi, chocolate</p><p>Drinks: coffee, tea, juice, wine</p><p>Transport: walking, driving, cycling</p>', 3),
  ('a2-l4', 'a2-course-id', 'Present and Past Continuous', '<h2>Ongoing Actions</h2><p>Express actions in progress</p><h3>Present Continuous</h3><p>I am working now. / Are you studying?</p><h3>Past Continuous</h3><p>I was sleeping when you called.</p><h3>Simple vs Continuous</h3><p>I worked (completed) vs I was working (in progress)</p><p>I work (habit) vs I am working (now)</p>', 4),
  ('a2-l5', 'a2-course-id', 'Can and Could for Ability', '<h2>Past and Present Abilities</h2><p>Compare what you can do now vs before</p><h3>Present Ability</h3><p>I can swim very well.</p><h3>Past Ability</h3><p>When I was young, I could run fast.</p><h3>Sports and Exercise Vocabulary</h3><ul><li>Swimming, running, cycling</li><li>Football, basketball, tennis</li><li>Gym, fitness, workout</li></ul>', 5),
  ('a2-l6', 'a2-course-id', 'Have To / Need To + Body Parts', '<h2>Obligations and Necessities</h2><p>Express what is necessary or required</p><h3>Modal Verbs</h3><ul><li>Have to / don''t have to</li><li>Need to / don''t need to</li><li>Must / mustn''t</li></ul><h3>Body Parts Vocabulary</h3><p>Head, shoulders, arms, hands, legs, feet, eyes, ears, nose, mouth</p><p><strong>Health context:</strong> "I have to see a doctor about my back."</p>', 6),
  ('a2-l7', 'a2-course-id', 'Present Perfect vs Simple Past', '<h2>Past with Present Connection</h2><p>Learn when to use Present Perfect</p><h3>Present Perfect</h3><p>I have lived here for 5 years. (still living here)</p><h3>Simple Past</h3><p>I lived there in 2015. (finished period)</p><h3>Irregular Verbs List</h3><p>go-went-gone, see-saw-seen, eat-ate-eaten, take-took-taken, make-made-made</p>', 7),
  ('a2-l8', 'a2-course-id', 'Present Perfect with Since/For', '<h2>Duration and Starting Point</h2><p>Express how long or from when</p><h3>Since vs For</h3><ul><li><strong>Since</strong> + point in time: since 2020, since Monday</li><li><strong>For</strong> + period of time: for 3 years, for a week</li></ul><h3>Examples</h3><p>I have worked here for two years.</p><p>She has been married since 2018.</p>', 8),
  ('a2-l9', 'a2-course-id', 'Present Perfect: Just/Ever/Already/Never/Yet', '<h2>Perfect Tense Adverbs</h2><p>Add specific meaning to Present Perfect</p><h3>Adverb Usage</h3><ul><li><strong>Just:</strong> I have just finished.</li><li><strong>Already:</strong> I have already eaten.</li><li><strong>Never:</strong> I have never been to Japan.</li><li><strong>Ever:</strong> Have you ever tried sushi?</li><li><strong>Yet:</strong> I haven''t finished yet.</li></ul>', 9),
  ('a2-l10', 'a2-course-id', 'Should vs Must + Travel Vocabulary', '<h2>Advice vs Obligation</h2><p>Give advice and express strong obligation</p><h3>Should</h3><p>You should study more. (advice)</p><h3>Must</h3><p>You must have a passport. (obligation/law)</p><h3>Travel Vocabulary</h3><ul><li>Airport, passport, luggage, flight</li><li>Hotel, reservation, check-in, check-out</li><li>Tourist, sightseeing, guidebook</li></ul>', 10),
  ('a2-l11', 'a2-course-id', 'Imperative + Participial Adjectives', '<h2>Commands and Feelings</h2><p>Give instructions and describe emotions</p><h3>Imperative</h3><p>Positive: Sit down. Open the window.</p><p>Negative: Don''t smoke. Don''t be late.</p><h3>-ed vs -ing Adjectives</h3><ul><li>I am bored. (how I feel)</li><li>The movie is boring. (what causes the feeling)</li><li>She is excited. / It''s exciting.</li></ul>', 11),
  ('a2-l12', 'a2-course-id', 'Comparatives', '<h2>Making Comparisons</h2><p>Compare two things</p><h3>Comparative Forms</h3><ul><li>Short adjectives: tall → taller</li><li>Long adjectives: beautiful → more beautiful</li><li>Irregular: good → better, bad → worse</li></ul><h3>Patterns</h3><p>as...as: She is as tall as her sister.</p><p>more/less: This car is more expensive.</p>', 12),
  ('a2-l13', 'a2-course-id', 'Superlatives', '<h2>The Best, Worst, Biggest...</h2><p>Express the highest degree</p><h3>Superlative Forms</h3><ul><li>Short: the tallest, the biggest</li><li>Long: the most beautiful, the most expensive</li><li>Irregular: the best, the worst</li></ul><h3>Usage</h3><p>This is the best restaurant in the city.</p><p>She is the most intelligent student.</p>', 13),
  ('a2-l14', 'a2-course-id', 'Used To + Health and Fitness', '<h2>Past Habits and States</h2><p>Talk about things that were different in the past</p><h3>Used To</h3><p>I used to live in Rio. (but not now)</p><p>Did you use to play soccer?</p><p>I didn''t use to like vegetables.</p><h3>Health and Fitness Collocations</h3><ul><li>Do exercise, go jogging</li><li>Eat healthy food, drink water</li><li>Get enough sleep, reduce stress</li></ul>', 14),
  ('a2-l15', 'a2-course-id', 'Passive Voice: Present and Past', '<h2>Focus on the Action, Not the Doer</h2><p>Learn when and how to use passive voice</p><h3>Formation</h3><p>Present: The car is repaired every month.</p><p>Past: The house was built in 1995.</p><h3>When to Use</h3><ul><li>Unknown doer: My bike was stolen.</li><li>Unimportant doer: English is spoken worldwide.</li></ul><h3>Art Vocabulary</h3><p>painting, sculpture, museum, gallery, artist, masterpiece</p>', 15),
  ('a2-l16', 'a2-course-id', 'First Conditional', '<h2>Real Future Possibilities</h2><p>Talk about likely future situations</p><h3>Structure</h3><p>If + present simple, will + base verb</p><h3>Examples</h3><ul><li>If it rains, I will stay home.</li><li>If you study hard, you will pass the test.</li><li>What will you do if you miss the bus?</li></ul><h3>Usage</h3><p>For real, possible situations in the future.</p>', 16),
  ('a2-l17', 'a2-course-id', 'Second Conditional', '<h2>Imaginary Situations</h2><p>Talk about hypothetical or unlikely situations</p><h3>Structure</h3><p>If + past simple, would + base verb</p><h3>Examples</h3><ul><li>If I won the lottery, I would travel the world.</li><li>If I were you, I would apologize.</li><li>What would you do if you met a celebrity?</li></ul>', 17),
  ('a2-l18', 'a2-course-id', 'Infinitive and Gerund Verbs', '<h2>Verb Patterns</h2><p>Learn which verbs are followed by infinitive or gerund</p><h3>Infinitive (to + verb)</h3><p>I want to learn English. / I decided to leave.</p><h3>Gerund (verb + ing)</h3><p>I enjoy reading. / I finished working.</p><h3>Common Patterns</h3><ul><li>Like/love/hate + both</li><li>Want/need/decide + infinitive</li><li>Enjoy/finish/mind + gerund</li></ul>', 18),
  ('a2-l19', 'a2-course-id', 'Phrasal Verbs Introduction', '<h2>Multi-word Verbs</h2><p>Learn common phrasal verbs</p><h3>Common Phrasal Verbs</h3><ul><li>Get up, wake up, turn on/off</li><li>Look for, look after, look forward to</li><li>Put on, take off, try on</li><li>Give up, carry on, work out</li></ul><h3>Separable vs Inseparable</h3><p>Turn on the TV / Turn the TV on</p><p>Look after the children (inseparable)</p>', 19),
  ('a2-l20', 'a2-course-id', 'Quantifiers: Too/Enough/So/Such', '<h2>Expressing Degree and Amount</h2><p>Show if something is sufficient or excessive</p><h3>Too + adjective/adverb</h3><p>This coffee is too hot. (excessive)</p><h3>Adjective + enough</h3><p>This coffee is hot enough. (sufficient)</p><h3>So vs Such</h3><p>So + adjective: so hot</p><p>Such + noun: such a hot day</p>', 20);

-- Continue with B1, B2, C1, C2 lessons...
-- (I'll create a shorter version for brevity, but you can expand based on the curriculum)

INSERT INTO lessons (id, course_id, title, content, order_index) VALUES
  ('b1-l1', 'b1-course-id', 'Advanced Grammar Review', '<h2>Consolidating Intermediate Skills</h2><p>Review and strengthen A2 grammar with complex exercises</p>', 1),
  ('b1-l2', 'b1-course-id', 'Complex Sentence Structures', '<h2>Building More Sophisticated Sentences</h2><p>Learn to create complex, compound sentences</p>', 2),
  ('b1-l3', 'b1-course-id', 'Advanced Modal Verbs', '<h2>Expressing Probability and Deduction</h2><p>Must, might, could, can''t for deduction</p>', 3);

INSERT INTO lessons (id, course_id, title, content, order_index) VALUES
  ('b2-l1', 'b2-course-id', 'Conversation Topics + Grammar Review', '<h2>Advanced Discussion Skills</h2><p>Practice complex conversations while reviewing all tenses</p>', 1),
  ('b2-l2', 'b2-course-id', 'Future Time Clauses + Conditionals', '<h2>Complex Future Structures</h2><p>When, as soon as, before, after + future meanings</p>', 2),
  ('b2-l3', 'b2-course-id', 'Present Perfect Simple vs Continuous', '<h2>Subtle Differences in Perfect Tenses</h2><p>I have worked vs I have been working</p>', 3);

INSERT INTO lessons (id, course_id, title, content, order_index) VALUES
  ('c1-l1', 'c1-course-id', 'Advanced Discourse Markers', '<h2>Sophisticated Communication</h2><p>Furthermore, nevertheless, consequently, etc.</p>', 1),
  ('c1-l2', 'c1-course-id', 'Nuanced Grammar Structures', '<h2>Advanced Grammar Patterns</h2><p>Inversion, cleft sentences, advanced conditionals</p>', 2),
  ('c1-l3', 'c1-course-id', 'Idiomatic Expressions', '<h2>Natural English Usage</h2><p>Master idioms and colloquial expressions</p>', 3);

INSERT INTO lessons (id, course_id, title, content, order_index) VALUES
  ('c2-l1', 'c2-course-id', 'Near-Native Fluency', '<h2>Mastering Subtle Language Differences</h2><p>Achieve native-like precision in communication</p>', 1),
  ('c2-l2', 'c2-course-id', 'Academic and Professional English', '<h2>Formal Register and Style</h2><p>Master formal, academic, and professional communication</p>', 2),
  ('c2-l3', 'c2-course-id', 'Literary Analysis and Critical Thinking', '<h2>Advanced Text Analysis</h2><p>Analyze complex texts with sophisticated vocabulary</p>', 3);