// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://frbmvljizolvxcxdkefa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZyYm12bGppem9sdnhjeGRrZWZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4OTI2MjIsImV4cCI6MjA3MTQ2ODYyMn0.xfmKb2qQmHU3PDwQIhbHCp0cyRhyN-FPikZRa_apzpA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});